/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать сессию по данным запуска MAX (initData) */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Завершить текущую сессию */
        delete: operations["deleteCurrentSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь, его организации и состояние канала напоминаний */
        get: operations["getMe"];
        put?: never;
        post?: never;
        /** Удалить аккаунт и все организации, где пользователь — владелец */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Справочники (виды деятельности, регионы, признаки, типы документов) */
        get: operations["getCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать организацию (текущий пользователь становится владельцем) */
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        /** Организация и сводка статусов документов */
        get: operations["getOrganization"];
        put?: never;
        post?: never;
        /** Удалить организацию со всеми документами, участниками и напоминаниями */
        delete: operations["deleteOrganization"];
        options?: never;
        head?: never;
        /** Изменить профиль организации (оптимистичная блокировка по version) */
        patch: operations["updateOrganization"];
        trace?: never;
    };
    "/organizations/{organizationId}/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        /** Типовые документы по профилю, ещё не добавленные в реестр */
        get: operations["listSuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        /** Реестр документов, отсортированный по сроку (ближайшие первыми, бессрочные в конце) */
        get: operations["listDocuments"];
        put?: never;
        /** Добавить документ (идемпотентно по id) */
        post: operations["createDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/documents/batch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Пакетное добавление 1–30 документов в одной транзакции (онбординг) */
        post: operations["createDocumentsBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        /** Карточка документа с историей периодов и шагами продления */
        get: operations["getDocument"];
        put?: never;
        post?: never;
        /** Удалить документ вместе с периодами и напоминаниями */
        delete: operations["deleteDocument"];
        options?: never;
        head?: never;
        /** Изменить реквизиты, исправить даты текущего периода, отступы напоминаний */
        patch: operations["updateDocument"];
        trace?: never;
    };
    "/documents/{documentId}/renewals": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Продлить документ — создать новый текущий период (идемпотентно по id периода) */
        post: operations["renewDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        /** Участники организации */
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/members/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Исключить участника (владелец) или выйти из организации (сам участник, не владелец) */
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        /** Сменить роль участника (только владелец; роль владельца не меняется) */
        patch: operations["updateMemberRole"];
        trace?: never;
    };
    "/organizations/{organizationId}/notification-settings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        /** Мои настройки напоминаний в этой организации */
        get: operations["getMyNotificationSettings"];
        /** Изменить мои настройки напоминаний (перепланирует мои напоминания) */
        put: operations["putMyNotificationSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        /** Активные приглашения (без ссылок — токен хранится только в виде хеша) */
        get: operations["listInvites"];
        put?: never;
        /** Создать одноразовое приглашение и ссылку-диплинк на мини-приложение */
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{inviteId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Отозвать приглашение */
        delete: operations["revokeInvite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Показать, куда приглашают, до принятия */
        post: operations["previewInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Принять приглашение (одноразово) */
        post: operations["acceptInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/exports/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Подготовить одноразовую ссылку на ICS-файл сроков для WebApp.downloadFile */
        post: operations["createCalendarExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/downloads/{downloadToken}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                downloadToken: string;
            };
            cookie?: never;
        };
        /** Скачать ICS по одноразовой ссылке (без Bearer; не более 3 скачиваний за 10 минут) */
        get: operations["downloadCalendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Технические события клиента (ошибки запуска, ошибки MAX Bridge, длительность bootstrap) */
        post: operations["postClientEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        Uuid: string;
        /**
         * Format: date
         * @description Календарная дата в часовом поясе организации
         */
        LocalDate: string;
        /** @enum {string} */
        Role: "owner" | "editor" | "viewer";
        /** @enum {string} */
        InvitableRole: "editor" | "viewer";
        /**
         * @description expired — срок раньше сегодняшней даты; expiring — ≤ 30 дней; valid — > 30 дней; no_expiry — бессрочный
         * @enum {string}
         */
        DeadlineStatus: "expired" | "expiring" | "valid" | "no_expiry";
        /**
         * @description model — модельные данные справочника, не сверенные с первоисточником
         * @enum {string}
         */
        DataStatus: "model" | "verified";
        /** @enum {string} */
        Platform: "ios" | "android" | "desktop" | "web";
        /**
         * @description unavailable — сервис bot не ответил за отведённое время
         * @enum {string}
         */
        RecipientState: "unknown" | "active" | "muted" | "stopped" | "unreachable" | "unavailable";
        /**
         * @description Состояние плана напоминаний для документа: actual — reminders-service учёл последнее изменение; pending — изменение ещё не доставлено; unavailable — план временно недоступен.
         * @enum {string}
         */
        RemindersState: "actual" | "pending" | "unavailable";
        /** @enum {string} */
        ErrorCode: "VALIDATION_FAILED" | "UNAUTHENTICATED" | "LAUNCH_DATA_INVALID" | "LAUNCH_DATA_EXPIRED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT_VERSION" | "CONFLICT_ID_REUSED" | "INVITE_INVALID" | "INVITE_EXPIRED" | "ALREADY_MEMBER" | "QUOTA_EXCEEDED" | "LINK_GONE" | "RATE_LIMITED" | "OVERLOADED" | "DEPENDENCY_UNAVAILABLE" | "INTERNAL";
        FieldError: {
            field: string;
            /** @enum {string} */
            code: "required" | "too_long" | "too_short" | "invalid_format" | "out_of_range" | "not_unique" | "unknown_value" | "invalid_combination";
            message: string;
        };
        Problem: {
            /**
             * Format: uri
             * @example urn:vovremya:problem:validation-failed
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            code: components["schemas"]["ErrorCode"];
            request_id: string;
            errors?: components["schemas"]["FieldError"][];
        };
        SessionCreateRequest: {
            /** @description Значение window.WebApp.initData без изменений */
            init_data: string;
            platform?: components["schemas"]["Platform"];
            app_version?: string;
        };
        /** @description Разобранный start_param из проверенных данных запуска */
        StartTarget: {
            /** @enum {string} */
            kind: "none" | "document" | "organization" | "invite";
            document_id?: components["schemas"]["Uuid"];
            organization_id?: components["schemas"]["Uuid"];
            invite_token?: string;
        };
        Account: {
            id: components["schemas"]["Uuid"];
            first_name: string;
            last_name: string | null;
            username: string | null;
        };
        Session: {
            token: string;
            /** Format: date-time */
            expires_at: string;
            account: components["schemas"]["Account"];
            start: components["schemas"]["StartTarget"];
        };
        MembershipSummary: {
            organization_id: components["schemas"]["Uuid"];
            organization_name: string;
            role: components["schemas"]["Role"];
            notify_enabled: boolean;
        };
        RemindersChannel: {
            state: components["schemas"]["RecipientState"];
            /** @description https://max.ru/<botName> — открыть через WebApp.openMaxLink */
            bot_chat_url: string | null;
        };
        Limits: {
            /** @constant */
            max_organizations: 20;
            /** @constant */
            max_documents_per_organization: 500;
            /** @constant */
            max_members_per_organization: 30;
            /** @constant */
            max_reminder_offsets: 5;
        };
        Me: {
            account: components["schemas"]["Account"];
            memberships: components["schemas"]["MembershipSummary"][];
            reminders_channel: components["schemas"]["RemindersChannel"];
            limits: components["schemas"]["Limits"];
        };
        BusinessCategory: {
            code: string;
            title: string;
        };
        Region: {
            code: string;
            title: string;
            default_timezone: string;
        };
        Feature: {
            code: string;
            question: string;
            hint: string | null;
        };
        CatalogSource: {
            title: string;
            /** Format: uri */
            url: string;
            checked_on: components["schemas"]["LocalDate"] | null;
        };
        DocumentType: {
            code: string;
            title: string;
            description: string;
            data_status: components["schemas"]["DataStatus"];
            source: components["schemas"]["CatalogSource"] | null;
            default_reminder_offsets_days: number[];
            renewal_steps: string[];
        };
        Catalog: {
            version: string;
            business_categories: components["schemas"]["BusinessCategory"][];
            regions: components["schemas"]["Region"][];
            features: components["schemas"]["Feature"][];
            document_types: components["schemas"]["DocumentType"][];
        };
        FeatureCodes: string[];
        OrganizationCreate: {
            id: components["schemas"]["Uuid"];
            name: string;
            business_category_code: string;
            region_code: string;
            /** @description IANA, например Europe/Moscow */
            timezone: string;
            feature_codes: components["schemas"]["FeatureCodes"];
        };
        OrganizationUpdate: {
            expected_version: number;
            name?: string;
            business_category_code?: string;
            region_code?: string;
            timezone?: string;
            feature_codes?: components["schemas"]["FeatureCodes"];
        };
        DocumentStats: {
            total: number;
            expired: number;
            expiring: number;
            valid: number;
            no_expiry: number;
            next_valid_until: components["schemas"]["LocalDate"] | null;
        };
        Organization: {
            id: components["schemas"]["Uuid"];
            name: string;
            business_category_code: string;
            region_code: string;
            timezone: string;
            feature_codes: components["schemas"]["FeatureCodes"];
            my_role: components["schemas"]["Role"];
            version: number;
            stats: components["schemas"]["DocumentStats"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Suggestion: {
            document_type_code: string;
            title: string;
            description: string;
            data_status: components["schemas"]["DataStatus"];
        };
        SuggestionList: {
            items: components["schemas"]["Suggestion"][];
        };
        /** @description За сколько дней до окончания срока напоминать; 0 — в день окончания */
        ReminderOffsets: number[];
        NullableShortText: string | null;
        DocumentCreate: {
            id: components["schemas"]["Uuid"];
            document_type_code?: string | null;
            title: string;
            number?: string | null;
            issuer?: string | null;
            /** @description Должность или условное обозначение; ФИО и иные ПДн не вводить */
            responsible_label?: string | null;
            notes?: string | null;
            reference_url?: string | null;
            valid_from?: components["schemas"]["LocalDate"] | null;
            valid_until?: components["schemas"]["LocalDate"] | null;
            reminder_offsets_days?: components["schemas"]["ReminderOffsets"];
        };
        DocumentsBatchCreate: {
            items: components["schemas"]["DocumentCreate"][];
        };
        DocumentsBatchResult: {
            items: components["schemas"]["Document"][];
        };
        /** @description Отсутствующее поле не меняется; null очищает необязательное поле */
        DocumentUpdate: {
            expected_version: number;
            title?: string;
            number?: string | null;
            issuer?: string | null;
            responsible_label?: string | null;
            notes?: string | null;
            reference_url?: string | null;
            valid_from?: components["schemas"]["LocalDate"] | null;
            valid_until?: components["schemas"]["LocalDate"] | null;
            reminder_offsets_days?: components["schemas"]["ReminderOffsets"];
        };
        RenewalCreate: {
            id: components["schemas"]["Uuid"];
            valid_from: components["schemas"]["LocalDate"] | null;
            valid_until: components["schemas"]["LocalDate"] | null;
        };
        Period: {
            id: components["schemas"]["Uuid"];
            valid_from: components["schemas"]["LocalDate"] | null;
            valid_until: components["schemas"]["LocalDate"] | null;
            is_current: boolean;
            /** Format: date-time */
            created_at: string;
        };
        DocumentListItem: {
            id: components["schemas"]["Uuid"];
            organization_id: components["schemas"]["Uuid"];
            document_type_code: string | null;
            title: string;
            responsible_label: string | null;
            valid_until: components["schemas"]["LocalDate"] | null;
            status: components["schemas"]["DeadlineStatus"];
            /** @description valid_until − сегодня в днях; отрицательно для просроченных; null для бессрочных */
            days_left: number | null;
            /**
             * Format: date-time
             * @description Ближайшее запланированное напоминание текущему пользователю; null, если план недоступен
             */
            next_reminder_at: string | null;
            reminders_state: components["schemas"]["RemindersState"];
        };
        DocumentPage: {
            items: components["schemas"]["DocumentListItem"][];
            next_cursor: string | null;
        };
        Document: {
            id: components["schemas"]["Uuid"];
            organization_id: components["schemas"]["Uuid"];
            document_type_code: string | null;
            title: string;
            number: string | null;
            issuer: string | null;
            responsible_label: string | null;
            notes: string | null;
            reference_url: string | null;
            current_period: components["schemas"]["Period"];
            /** @description Все периоды, новые первыми, не более 20 */
            periods: components["schemas"]["Period"][];
            status: components["schemas"]["DeadlineStatus"];
            days_left: number | null;
            reminder_offsets_days: components["schemas"]["ReminderOffsets"];
            /** Format: date-time */
            next_reminder_at: string | null;
            reminders_state: components["schemas"]["RemindersState"];
            renewal_steps: string[];
            data_status: components["schemas"]["DataStatus"] | null;
            version: number;
            can_edit: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Member: {
            account_id: components["schemas"]["Uuid"];
            first_name: string;
            last_name: string | null;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            joined_at: string;
            is_me: boolean;
        };
        MemberList: {
            items: components["schemas"]["Member"][];
        };
        MemberRoleUpdate: {
            role: components["schemas"]["InvitableRole"];
        };
        NotificationSettings: {
            enabled: boolean;
            /** @description Время напоминаний в часовом поясе организации */
            local_time: string;
        };
        InviteCreate: {
            id: components["schemas"]["Uuid"];
            role: components["schemas"]["InvitableRole"];
        };
        InviteCreated: {
            id: components["schemas"]["Uuid"];
            role: components["schemas"]["InvitableRole"];
            /** Format: date-time */
            expires_at: string;
            /** @description https://max.ru/<botName>?startapp=inv_<token> */
            link_url: string;
            share_text: string;
        };
        InviteSummary: {
            id: components["schemas"]["Uuid"];
            role: components["schemas"]["InvitableRole"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at: string;
            created_by_first_name: string | null;
        };
        InviteList: {
            items: components["schemas"]["InviteSummary"][];
        };
        InviteTokenRequest: {
            token: string;
        };
        InvitePreview: {
            organization_name: string;
            role: components["schemas"]["InvitableRole"];
            inviter_first_name: string | null;
            /** Format: date-time */
            expires_at: string;
        };
        InviteAccepted: {
            organization_id: components["schemas"]["Uuid"];
            role: components["schemas"]["InvitableRole"];
        };
        CalendarExport: {
            download_url: string;
            file_name: string;
            /** Format: date-time */
            expires_at: string;
        };
        ClientEvent: {
            /** @enum {string} */
            name: "bootstrap_completed" | "bootstrap_failed" | "bridge_error" | "api_error_shown";
            platform?: components["schemas"]["Platform"];
            app_version?: string;
            duration_ms?: number;
            code?: string;
        };
        ClientEventBatch: {
            events: components["schemas"]["ClientEvent"][];
        };
    };
    responses: {
        /** @description Некорректный запрос или ошибка валидации (VALIDATION_FAILED) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Нет/недействителен токен (UNAUTHENTICATED) или initData (LAUNCH_DATA_INVALID, LAUNCH_DATA_EXPIRED) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Недостаточно прав роли (FORBIDDEN) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Ресурс не найден или недоступен пользователю (NOT_FOUND, INVITE_INVALID) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Конфликт версии, повторное использование id, квота, повторное членство */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Превышен лимит запросов (RATE_LIMITED) */
        TooManyRequests: {
            headers: {
                "Retry-After": components["headers"]["Retry-After"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Иная ошибка (RATE_LIMITED, OVERLOADED, DEPENDENCY_UNAVAILABLE, INTERNAL) */
        Unexpected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Перегрузка (OVERLOADED) или недоступна зависимость (DEPENDENCY_UNAVAILABLE) */
        Unavailable: {
            headers: {
                "Retry-After": components["headers"]["Retry-After"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        OrganizationId: string;
        DocumentId: string;
        AccountId: string;
    };
    requestBodies: never;
    headers: {
        /** @description Идентификатор запроса (генерирует edge), повторяется в problem.request_id */
        "X-Request-Id": string;
        /** @description Через сколько секунд повторить запрос */
        "Retry-After": number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreateRequest"];
            };
        };
        responses: {
            /** @description Сессия создана */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["Unavailable"];
            default: components["responses"]["Unexpected"];
        };
    };
    deleteCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сессия отозвана */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["Unexpected"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["Unexpected"];
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Аккаунт и связанные данные удалены */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["Unexpected"];
        };
    };
    getCatalog: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    ETag?: string;
                    "Cache-Control"?: "private, max-age=3600";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
            /** @description Справочник не изменился */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["Unexpected"];
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreate"];
            };
        };
        responses: {
            /** @description Повтор идемпотентного запроса, организация уже создана */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            /** @description Создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["Unexpected"];
        };
    };
    getOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Unexpected"];
        };
    };
    deleteOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалена */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Unexpected"];
        };
    };
    updateOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            default: components["responses"]["Unexpected"];
        };
    };
    listSuggestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Unexpected"];
        };
    };
    listDocuments: {
        parameters: {
            query?: {
                status?: components["schemas"]["DeadlineStatus"];
                /** @description Поиск подстроки в названии без учёта регистра */
                q?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Unexpected"];
        };
    };
    createDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentCreate"];
            };
        };
        responses: {
            /** @description Повтор идемпотентного запроса */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            default: components["responses"]["Unexpected"];
        };
    };
    createDocumentsBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentsBatchCreate"];
            };
        };
        responses: {
            /** @description Все документы созданы или уже существовали с тем же содержимым */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentsBatchResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            default: components["responses"]["Unexpected"];
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Unexpected"];
        };
    };
    deleteDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалён */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Unexpected"];
        };
    };
    updateDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            default: components["responses"]["Unexpected"];
        };
    };
    renewDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenewalCreate"];
            };
        };
        responses: {
            /** @description Повтор идемпотентного запроса */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Период создан, напоминания перепланированы */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            default: components["responses"]["Unexpected"];
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Unexpected"];
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Участник удалён */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Unexpected"];
        };
    };
    updateMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberRoleUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Unexpected"];
        };
    };
    getMyNotificationSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Unexpected"];
        };
    };
    putMyNotificationSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationSettings"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettings"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Unexpected"];
        };
    };
    listInvites: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Unexpected"];
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteCreate"];
            };
        };
        responses: {
            /** @description Создано. Ссылка возвращается только в этом ответе. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteCreated"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
            default: components["responses"]["Unexpected"];
        };
    };
    revokeInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Отозвано */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            default: components["responses"]["Unexpected"];
        };
    };
    previewInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteTokenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitePreview"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["Unexpected"];
        };
    };
    acceptInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteTokenRequest"];
            };
        };
        responses: {
            /** @description Пользователь добавлен в организацию */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["Unexpected"];
        };
    };
    createCalendarExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ссылка создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarExport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["Unexpected"];
        };
    };
    downloadCalendar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                downloadToken: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Файл календаря */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "text/calendar": string;
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Ссылка истекла или исчерпана */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Unexpected"];
        };
    };
    postClientEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientEventBatch"];
            };
        };
        responses: {
            /** @description Принято */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["Unexpected"];
        };
    };
}
